version: "3.9"

networks:
  back-end:
    driver: bridge
services:
  angular:
    container_name: "gestioncinema_angular"
    build: .
    ports:
      - "4200:4200"
      
    volumes:
      - "/app/node_modules"
      - ".:/app"
    networks:
      - back-end